/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { Fragment, useEffect } from "react";
import AOS from "aos";
import Navbar from "../components/group/Navbar";
import Hero from "../components/group/Hero";
import TransactionSteps from "../components/group/TransactionSteps";
import Games from "../components/group/Games/Games";
import Reached from "../components/group/Reached/Reached";
import Story from "../components/group/Story/Story";
import Footer from "../components/group/Footer/Footer";

export default function Home() {
  useEffect(() => {
    AOS.init({
      once: true,
    });
  }, []);

  return (
    <Fragment>
      <Head>
        <title>TopStore</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <!-- Navbar --> */}
        <Navbar />

        {/* <!-- Hero --> */}
        <Hero />

        {/* <!-- 3 Column - Feature --> */}
        <TransactionSteps />

        {/* <!-- 5 Column - Featured-game --> */}
        <Games />

        {/* <!-- Reached --> */}
        <Reached />

        {/* <!-- Story --> */}
        <Story />

        {/* <!-- Footer --> */}
        <Footer />
      </main>
    </Fragment>
  );
}
